name: Build and Release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build script
      if: runner.os == 'Windows'
      run: .\build-win.bat

    - name: Archive Release Asset
      if: runner.os == 'Windows'
      run: Compress-Archive -Path ./dist/Daq122 -DestinationPath ./dist/Daq122_${{ runner.os }}_${{ matrix.arch }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Daq122_${{ runner.os }}_${{ matrix.arch }}
        path: ./dist/Daq122_${{ runner.os }}_${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: Daq122_Windows_x86

    - name: List contents
      run: ls -l .
      shell: bash

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Daq122_Windows_x86.zip